[tool.poetry]
name = "ai-cup"
version = "0.1.0"
description = ""
authors = ["energybubu <ivanhoward011878@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cohere = "^5.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
